services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/media/config/radarr:/config
      - /mnt/media/movies:/movies #optional
      - /mnt/media/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/media/config/sonarr/config
      - /mnt/media/tvshows:/tv #optional
      - /mnt/media/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/media/config/readarr:/config
      - /mnt/media/books:/books #optional
      - /mnt/media/downloads:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TTZ=America/Los_Angeles
      - NZBGET_USER=toor #optional
      - NZBGET_PASS=7ujm&UJM #optional
    volumes:
      - /mnt/media/config/nzbget:/config
      - /mnt/media/downloads/:/downloads #optional
    ports:
      - 6789:6789
    restart: unless-stopped
